# Generated by Django 5.1.4 on 2026-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahikhata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahikhata',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
