# Generated by Django 4.2.7 on 2025-09-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seennotification',
            name='seen',
        ),
        migrations.AlterField(
            model_name='seennotification',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_notes', to='home.notification'),
        ),
    ]
