# Generated by Django 4.2.7 on 2025-09-29 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_invoice_amount_remove_invoice_pending_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(120.0)]),
        ),
    ]
