# Generated by Django 5.1.4 on 2025-10-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_invoice_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
