# Generated by Django 5.1.4 on 2025-10-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_clinic_clinic_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic',
            new_name='users',
        ),
    ]
