# Generated by Django 5.1.4 on 2025-10-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_clinic_clinic_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='home.clinic'),
        ),
    ]
